CONTENT_TYPES = [
    "text/csv",
    "text/html",
    # "text/javascript",
    "text/xml",
    "text/plain",
    "application/json",
    "application/xml",
    "application/zip",
    "application/x-www-form-urlencoded",
    "multipart/form-data",
]

SEARCH_WORDS = [
    "marker",
    "address",
    "city",
    "lat",
    "lon",
    "point",
    "place",
    "latitude",
    "longitude",
    "long",
    "addrs",
    "location",
    "feature",
    "features",
    "featurecollection",
    "geometry",
    "geom",
    "coord",
    "coordinates",
    "coords",
    "properties",
]